### ISSUE TITLE
Code signing error for scripts

### ISSUE THREAD

**Issue by cocoatoucher** [bugsee/spm#1]
I get a code signing error for below files when trying to upload an archive to App Store. They probably need to be excluded as resources in Package.swift specification

xcarchive/.../Frameworks/Bugsee.framework/Tools/Bugsee_archive_phase.sh:#!/bin/sh
xcarchive/.../Frameworks/Bugsee.framework/Tools/BugseeClean:#!/usr/bin/python
xcarchive/.../Frameworks/Bugsee.framework/Tools/Bugsee_build_phase.sh:#!/bin/sh
xcarchive/.../Frameworks/Bugsee.framework/Tools/BugseeAgent:#!/usr/bin/python

**Comment by dsheikherev** [comment]
This issue is fixed and does not occur since v2.1.0
